spring:
  output:
    ansi:
      enabled: always
  config:
    activate:
      on-profile: h2
  datasource:
    url: "jdbc:h2:mem:jcheck;MODE=MYSQL;"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
    data: classpath:import.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jwt:
    secret: cc24857e2d929b1c014f9b0ec9813d294d31fc5bc838f62b69a76203f9f49072
---
