spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: "jdbc:h2:mem:jcheck;MODE=MYSQL;"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
---
